In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist,squareform

In [2]:
#read_data
movies_df = pd.read_csv('movies.csv')

In [3]:
#explore the data
movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
#preprocessing
expanded_data = []
for i in range(len(movies_df)):
    # Extract title without year
    title = movies_df.loc[i, 'title'].split(" (")[0]
    #split the genres
    genres = movies_df.loc[i, 'genres'].split('|')
    #doing one to many relationship see the result to understand
    for genre in genres:
        expanded_data.append({'title': title, 'genre': genre})

# Create new DataFrame with expanded rows
movies_df = pd.DataFrame(expanded_data)



In [7]:
#the result
movies_df

title      genre
0                         Toy Story  Adventure
1                         Toy Story  Animation
2                         Toy Story   Children
3                         Toy Story     Comedy
4                         Toy Story    Fantasy
...                             ...        ...
22079         No Game No Life: Zero    Fantasy
22080                         Flint      Drama
22081  Bungo Stray Dogs: Dead Apple     Action
22082  Bungo Stray Dogs: Dead Apple  Animation
22083  Andrew Dice Clay: Dice Rules     Comedy

[22084 rows x 2 columns]

In [8]:
#make it as table the rows is title and columns is genres
movies_df = pd.crosstab(movies_df['title'],movies_df['genre'])

In [9]:
#calculate jaccard distance the result 1d array
jaccard_dist=  pdist(movies_df.values,metric='jaccard')
#make it 2d array
squared_jaccard_dist = squareform(jaccard_dist)
#convert from distance to similarity which we foucs for
jaccard_similarity = 1- squared_jaccard_dist

In [10]:
#the result
print(jaccard_similarity)

[[1.         0.125      0.2        ... 0.4        0.         0.        ]
 [0.125      1.         0.         ... 0.14285714 0.16666667 0.16666667]
 [0.2        0.         1.         ... 0.         0.         0.33333333]
 ...
 [0.4        0.14285714 0.         ... 1.         0.         0.        ]
 [0.         0.16666667 0.         ... 0.         1.         0.33333333]
 [0.         0.16666667 0.33333333 ... 0.         0.33333333 1.        ]]


In [11]:
#make it as dataframe with title as column and row to get the relatio between two movies like
#distance_df['toy story']['jumanji']
distance_df = pd.DataFrame(jaccard_similarity,index =movies_df.index,columns=movies_df.index)

In [12]:
#the result
distance_df

title                                  '71  'Hellboy': The Seeds of Creation  \
title                                                                          
'71                               1.000000                          0.125000   
'Hellboy': The Seeds of Creation  0.125000                          1.000000   
'Round Midnight                   0.200000                          0.000000   
'Salem's Lot                      0.333333                          0.000000   
'Til There Was You                0.200000                          0.000000   
...                                    ...                               ...   
eXistenZ                          0.400000                          0.142857   
xXx                               0.400000                          0.142857   
xXx: State of the Union           0.400000                          0.142857   
¡Three Amigos!                    0.000000                          0.166667   
À nous la liberté                 0.000000                          0.166667   

title                             'Round Midnight  'Salem's Lot  \
title                                                             
'71                                      0.200000      0.333333   
'Hellboy': The Seeds of Creation         0.000000      0.000000   
'Round Midnight                          1.000000      0.200000   
'Salem's Lot                             0.200000      1.000000   
'Til There Was You                       0.333333      0.200000   
...                                           ...           ...   
eXistenZ                                 0.000000      0.166667   
xXx                                      0.000000      0.166667   
xXx: State of the Union                  0.000000      0.166667   
¡Three Amigos!                           0.000000      0.000000   
À nous la liberté                        0.333333      0.000000   

title                             'Til There Was You  \
title                                                  
'71                                         0.200000   
'Hellboy': The Seeds of Creation            0.000000   
'Round Midnight                             0.333333   
'Salem's Lot                                0.200000   
'Til There Was You                          1.000000   
...                                              ...   
eXistenZ                                    0.000000   
xXx                                         0.000000   
xXx: State of the Union                     0.000000   
¡Three Amigos!                              0.000000   
À nous la liberté                           0.000000   

title                             'Tis the Season for Love  'burbs, The  \
title                                                                     
'71                                                    0.0          0.0   
'Hellboy': The Seeds of Creation                       0.0          0.2   
'Round Midnight                                        0.0          0.0   
'Salem's Lot                                           0.0          0.0   
'Til There Was You                                     0.5          0.0   
...                                                    ...          ...   
eXistenZ                                               0.0          0.0   
xXx                                                    0.0          0.0   
xXx: State of the Union                                0.0          0.0   
¡Three Amigos!                                         0.0          0.5   
À nous la liberté                                      0.0          0.5   

title                             'night Mother  (500) Days of Summer  \
title                                                                   
'71                                        0.25              0.166667   
'Hellboy': The Seeds of Creation           0.00              0.142857   
'Round Midnight                            0.50              0.250000   
'Salem's Lot     

In [16]:
#testing
watched_movies = ['Toy Story','Jumanji']
testing = movies_df.reindex(watched_movies)

In [19]:
ans=[]
for i in range(len(watched_movies)):
  ans.append(distance_df[watched_movies[i]].sort_values(ascending=False)[:2])
print(ans)
#most 2 similer movies for toy sotry and jumanji as result

[title
Emperor's New Groove, The    1.0
Monsters, Inc.               1.0
Name: Toy Story, dtype: float64, title
Harry Potter and the Sorcerer's Stone        1.0
Chronicles of Narnia: Prince Caspian, The    1.0
Name: Jumanji, dtype: float64]
